# Generated by Django 5.2 on 2025-06-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserCommunicationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefers_email",
                    models.BooleanField(
                        default=True,
                        help_text="Does the user prefer email notifications?",
                    ),
                ),
                (
                    "prefers_in_app",
                    models.BooleanField(
                        default=True,
                        help_text="Does the user prefer in-app notifications?",
                    ),
                ),
                (
                    "default_channel",
                    models.CharField(
                        choices=[("email", "Email"), ("in_app", "In-App")],
                        default="in_app",
                        help_text="The primary channel for non-critical notifications.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Communication Preference",
                "verbose_name_plural": "User Communication Preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="ID of the user who will receive the notification.",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("in_app", "In-App")],
                        help_text="The delivery method (email or in-app).",
                        max_length=10,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        default="general",
                        help_text="A specific type identifier for the notification.",
                        max_length=50,
                    ),
                ),
                (
                    "message_data",
                    models.JSONField(
                        help_text="JSON payload containing all notification content (e.g., {'subject': '...', 'body': '...'} or {'title': '...', 'message': '...'})."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the notification job.",
                        max_length=10,
                    ),
                ),
                (
                    "retries_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this notification has been retried.",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum allowed retries before marking as failed.",
                    ),
                ),
                (
                    "failed_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for the last failure, if any.",
                        null=True,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the notification job was created/scheduled.",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was successfully sent.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update to the record.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Job",
                "verbose_name_plural": "Notification Jobs",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="notificatio_status_027399_idx",
                    )
                ],
            },
        ),
    ]
