# Generated by Django 5.2 on 2025-06-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationjob",
            name="is_read",
            field=models.BooleanField(
                default=False,
                help_text="For in-app notifications, indicates if the client has acknowledged receipt via WebSocket.",
            ),
        ),
    ]
